### ISSUE TITLE
Key Error: 'scopes'

### ISSUE THREAD

**Issue by rohaaan** [microsoftgraph/python-security-rest-sample#1]
error at this line(41)  
if 'SecurityEvents.Read.All' not in flask.session['scopes'] or 'SecurityEvents.ReadWrite.All' not in flask.session['scopes']:

how to add these in scopes array??

**Comment by edwardkoval** [comment]
It looks like you are either missing the permissions in your app registration at https://apps.dev.microsoft.com/ or your tenant admin hasn't given consent for your user to access the SecurityEvents in the tenant. Please read the [security-authorization](https://developer.microsoft.com/en-us/graph/docs/concepts/security-authorization) documentation for a more detailed explanation.

**Comment by edwardkoval** [comment]
@rohaaan, I'm having trouble recreating the issue, can you please provide a trace log? I think the issue is with your flask version.
