### ISSUE TITLE
Admin Consent Required

### ISSUE THREAD

**Issue by walshbm15** [microsoftgraph/python-security-rest-sample#2]
I am trying to run the example, however when trying to [get admin consent to view security data](https://github.com/microsoftgraph/python-security-rest-sample#get-admin-consent-to-view-security-data) I am shown your Tenant Admin has not given consent to this application. I have given `SecurityEvents.Read.All` and `SecurityEvents.ReadWrite.All` permissions from [this](https://apps.dev.microsoft.com) site. 

I am using a free Microsoft account created at https://www.outlook.com. Is there something I am missing or is this due to the nature of my account, where I would need a business account to access these permissions?

**Comment by edwardkoval** [comment]
Permissions can be a bit confusing when dealing with a multi-tenant application, any Microsoft account can be used to register an application at https://apps.dev.microsoft.com/. But that doesn't automatically give access to a Tenants data, when an application requires elevated permissions such as `SecurityEvents.Read.All `and `SecurityEvents.ReadWrite.All`. The tenant (company) admin must give consent for that application to access the tenant's data. Read over the [Authorization and the Microsoft Graph Security API](https://developer.microsoft.com/en-us/graph/docs/concepts/security-authorization) doc to better understand the app registration details. Then you may want to look into creating an Azure tenant to test your application. Most Microsoft security products that have integrated with the security api have a free trail that you could register to your tenant.

**Comment by walshbm15** [comment]
That was it, thanks.
