### ISSUE TITLE
Access Denied error and use version 2.0 of protocol

### ISSUE THREAD

**Issue by tariqrahiman** [microsoftgraph/python-security-rest-sample#4]
Hello,
I get an access denied error when i run the get to the step for "Get Admin consent to view Security data"
The error message in the URL reads Please+contact+the+application+vendor+as+they+need+to+use+version+2.0+of+the+protocol+to+support+this

How to use the version 2.0 of the protocol?

**Comment by preetikr** [comment]
Hi, Pertaining to this specific error message, it seems the application registration is not done correctly in this scenario. Did you register your application following the steps for 'Register an application in the Azure AD v2.0 endpoint' outlined @ https://docs.microsoft.com/en-us/graph/security-authorization ?

**Comment by tariqrahiman** [comment]
This is now fixed, after following the correct steps.
