### ISSUE TITLE
flask_session missing in requirements

### ISSUE THREAD

**Issue by johestephan** [microsoftgraph/python-security-rest-sample#8]
the requirements.txt does not include flask_session which is required by the sample.py

flask-session=0.3.1

should fix the issue

 ```
$ python3 sample.py 
Traceback (most recent call last):
  File "sample.py", line 17, in <module>
    from flask_session import Session
ModuleNotFoundError: No module named 'flask_session'

```

**Comment by chinguyen1** [comment]
@johestephan, flask-session has been added to the requirements.txt. Thanks for your feedback!
